FROM ubuntu
COPY udpgw /
COPY lightsocks-server /
ENV LIGHTSOCKS_SERVER_PORT 12315
EXPOSE 7300
EXPOSE ${LIGHTSOCKS_SERVER_PORT}
CMD bash -c "./udpgw --listen-addr 0.0.0.0:7300 &" && ./lightsocks-server
